//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.06.25 at 11:32:53 AM SAST 
//


package com.edu.schoolsoapapi.students;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.edu.schoolsoapapi.students package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.edu.schoolsoapapi.students
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link GetStudentDetailsResponse }
     * 
     */
    public GetStudentDetailsResponse createGetStudentDetailsResponse() {
        return new GetStudentDetailsResponse();
    }

    /**
     * Create an instance of {@link UpdateStudentDetailsRequest }
     * 
     */
    public UpdateStudentDetailsRequest createUpdateStudentDetailsRequest() {
        return new UpdateStudentDetailsRequest();
    }

    /**
     * Create an instance of {@link GetAllStudentDetailsResponse }
     * 
     */
    public GetAllStudentDetailsResponse createGetAllStudentDetailsResponse() {
        return new GetAllStudentDetailsResponse();
    }

    /**
     * Create an instance of {@link GetStudentDetailsRequest }
     * 
     */
    public GetStudentDetailsRequest createGetStudentDetailsRequest() {
        return new GetStudentDetailsRequest();
    }

    /**
     * Create an instance of {@link CreateStudentDetailsResponse }
     * 
     */
    public CreateStudentDetailsResponse createCreateStudentDetailsResponse() {
        return new CreateStudentDetailsResponse();
    }

    /**
     * Create an instance of {@link DeleteStudentDetailsRequest }
     * 
     */
    public DeleteStudentDetailsRequest createDeleteStudentDetailsRequest() {
        return new DeleteStudentDetailsRequest();
    }

    /**
     * Create an instance of {@link StudentDetails }
     * 
     */
    public StudentDetails createStudentDetails() {
        return new StudentDetails();
    }

    /**
     * Create an instance of {@link CreateStudentDetailsRequest }
     * 
     */
    public CreateStudentDetailsRequest createCreateStudentDetailsRequest() {
        return new CreateStudentDetailsRequest();
    }

    /**
     * Create an instance of {@link DeleteStudentDetailsResponse }
     * 
     */
    public DeleteStudentDetailsResponse createDeleteStudentDetailsResponse() {
        return new DeleteStudentDetailsResponse();
    }

    /**
     * Create an instance of {@link UpdateStudentDetailsResponse }
     * 
     */
    public UpdateStudentDetailsResponse createUpdateStudentDetailsResponse() {
        return new UpdateStudentDetailsResponse();
    }

    /**
     * Create an instance of {@link GetAllStudentDetailsRequest }
     * 
     */
    public GetAllStudentDetailsRequest createGetAllStudentDetailsRequest() {
        return new GetAllStudentDetailsRequest();
    }

}
